# Generated by Django 2.2.5 on 2019-09-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_sharing',
            field=models.BooleanField(default=False),
        ),
    ]
