# Generated by Django 2.2.6 on 2019-10-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_categories_sub_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='sub_types',
        ),
    ]
