# Generated by Django 2.2.6 on 2019-10-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_remove_categories_sub_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='sub_types',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='category.SubCategories'),
        ),
    ]
