# Generated by Django 2.2.6 on 2019-10-02 06:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('mobile_no', models.CharField(max_length=10, unique=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)])),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('avatar_url', models.ImageField(blank=True, default=None, null=True, upload_to='profile_img/')),
                ('is_approved', models.BooleanField(default=False)),
                ('has_applied', models.BooleanField(default=False)),
                ('document_proof', models.ImageField(blank=True, default=None, null=True, upload_to='document_proof/')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last logined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, default=None, null=True, to='category.Categories')),
                ('current_location', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', user.models.MyUserManager()),
            ],
        ),
    ]
