# Generated by Django 2.2.6 on 2019-10-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191012_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='categories',
        ),
    ]
