# Generated by Django 2.2.6 on 2019-10-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_categories_sub_types'),
        ('user', '0004_remove_user_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='category.SubCategories'),
        ),
    ]
