# Generated by Django 2.2.6 on 2019-10-15 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_sub_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='document_proof',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_applied',
        ),
    ]
