# Generated by Django 2.2.6 on 2019-10-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191016_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_description',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
