# Generated by Django 2.2.6 on 2019-10-15 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191016_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_approved',
            new_name='is_vendor',
        ),
    ]
