# Generated by Django 2.2.6 on 2019-10-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20191016_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sharing',
            field=models.BooleanField(default=False),
        ),
    ]
